---
- name: manage /etc/sysconfig/iptables
  copy: 
    src: iptables.conf
    dest: /etc/sysconfig/iptables 
    owner: root
    group: root
    mode: 0600

- name: manage /etc/sysctl.conf with ip forwarding and redirects enabled.
  copy: 
    src: sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644

- name: iptables-restore from file /etc/sysconfig/iptables
  shell: iptables-restore < /etc/sysconfig/iptables

- name: configure ip forwarding
  shell: echo 1 > /proc/sys/net/ipv4/ip_forward 

- name: configure ip redirects
  shell: echo 0 > /proc/sys/net/ipv4/conf/eth0/send_redirects

